### ISSUE TITLE
server certificate verification failed. CAfile: none CRLfile: none

### ISSUE THREAD

**Issue by alastairUK** [lpenz/ghaction-cmake#1]
When I attempt to use this action on my project I see the error above when the CMake tries to grab GoogleTest from
https://github.com/google/googletest.git

As per:
https://github.com/alastairUK/p528/commit/c94be9216ffc20f3a714dd843c6957e0583758f1/checks?check_suite_id=290869965

**Comment by lpenz** [comment]
Can you please try adding `ca-certificates` as a a dependency? Like so:

      - uses: docker://lpenz/ghaction-cmake:latest
        with:
          dependencies: ca-certificates

**Comment by alastairUK** [comment]
Yes that gets rid of that error. Many thanks.

I now have other ones to get rid of. Looks like pthread issue  

https://github.com/alastairUK/p528/runs/284859099

**Comment by lpenz** [comment]
That's probably a missing `-pthread` in the compilation/linking, or the code is doing `-lgtest` *after* `-lpthread`. There's a stackoverflow question about it: https://stackoverflow.com/questions/21116622/undefined-reference-to-pthread-key-create-linker-error

I'm closing this issue, as the dependency line solved it.
