### ISSUE TITLE
Add gcc sanitizers

### ISSUE THREAD

**Issue by jayvdb** [lpenz/ghaction-cmake#17]
https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html

for bullseye's gcc-10 https://devdocs.io/gcc~10/instrumentation-options

**Comment by jayvdb** [comment]
I have a project which is failing on clang, so I am quite motivated to do the work to get these working.

**Comment by lpenz** [comment]
Sounds good to me
