### ISSUE TITLE
Install cmakelang

### ISSUE THREAD

**Issue by jayvdb** [lpenz/ghaction-cmake#5]
https://pypi.org/project/cmakelang/ (https://github.com/cheshirekow/cmake_format) provides cmake tools: a formatter, and a linter, and a ctest post-processor.  

It might be useful to have these tools available to promote standardisation of `.cmake` modules/`CMakeLists.txt`.

The Python runtime is already installed on the Docker images, so adding this package shouldnt increase its size by much.

**Comment by jayvdb** [comment]
fwiw, I recently integrated this to a repo with lots of `.cmake` files and found it worked quite well, with only one parsing problem. https://github.com/swift-nav/cmake/pull/96

It is part of https://github.com/TheLartians/Format.cmake , which is a component of https://github.com/TheLartians/ModernCppStarter

**Comment by lpenz** [comment]
I'm definitely going to look at this in the context of [lpenz/omnilint](http://github/lpenz/omnilint), just opened the pull request at https://github.com/lpenz/omnilint/issues/4. It's been a while since I touched it, but I do want to pick it up again.

Thanks for pointing it out
