### ISSUE TITLE
Docker tag 0.14 not like prior v0.x

### ISSUE THREAD

**Issue by jayvdb** [lpenz/ghaction-cmake#7]
The latest tag is `0.14` while previous ones are v0.x .

Also the README example still refers to v0.11

**Comment by jayvdb** [comment]
Docs have been updated to refer to `0.14`, so I guess that is the new naming convention.

**Comment by lpenz** [comment]
Yes
A while ago I looked around and figured that the `v` prefix is usually present in git tags, but is not that pervasive in other places. I've standardized on that.
